### ISSUE TITLE
your approaches doesn't work

### ISSUE THREAD

**Issue by ghost** [SBasalaev/alchemy-os#7] opened 2018-07-29 00:46 UTC
you have said Open the file "/cfg/pkg/sources" and change http://alchemy-os.org to http://alchemy-os.sourceforge.net/.but that doesn't work I hope you can update alchemy-os to a right version which can refresh lists correctly

**Comment by SBasalaev** [comment] 2018-08-02 06:48
Duplicate of #6

**Closed as completed by SBasalaev** 2018-08-02 06:48 UTC
Labels: duplicate

**Comment by SBasalaev** [comment] 2018-08-02 06:55
Sorry, Alchemy OS is abandoned since 2014, I don't publish any more updates. You can still try to download packages from http://alchemy-os.sourceforge.net/packages/2.1/ and install them by hand.
The command is (if I remember correctly)
```
pkg-arh install yourfile.pkg
```
